### ISSUE TITLE
Web Socket for Web UI 'Positions' disconnecting

### ISSUE THREAD

**Issue by laisee** [Power-Trade/api-docs#8]
Web Socket connections dropping for 'Positions' after web app open for some time. See screenshots in attached doc. The disconnections happen after about 15-20 mins in Web UI. 

![image](https://github.com/Power-Trade/api-docs/assets/5905130/6e18d00b-d4ef-4108-9a36-369212d99c71)

[power-trade-issues-websockets-disconnection.pdf](https://github.com/Power-Trade/api-docs/files/14110239/power-trade-issues-websockets-disconnection.pdf)

**Comment by laisee** [comment]
comments on this one: "... a new positions api and there’s a cache issue on the server side that publishes positions. .. A fix is in test."

**Comment by klugjo** [comment]
Thanks @laisee having a look

**Comment by kernelbee** [comment]
@laisee : it can be when we re-deploy API backend... please provide env (url) and time of occurance (next time maybe)

**Comment by klugjo** [comment]
@laisee the GUI will try to reconnect periodically (with randomized, increasing time intervals as detailed here: https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/)

Unless we have an outage, a web app refresh should solve this

**Comment by laisee** [comment]
@klugjo Yes, a full refresh of the web page fixes the issue. I'm not seeing any behavior to re-connect at increasing intervals. Will test again and share details on date/time, browser, OS, etc. Until now I am using brave on OSX/M2.

**Comment by laisee** [comment]
From M: "We just moved to a new positions api and there’s a cache issue on the server side that publishes positions. This may be delayed. A fix is in test"

**Comment by laisee** [comment]
Any updates on this? I can still see 'Positions' websocket seems to fail on web UI if the user does nothing for 10 mins or longer. The current code doesn't seem to be re-trying or re-connecting for the disconnected socket.

**Comment by klugjo** [comment]
Fixed in TEST environment and testing, will let you know when deployed to Production. Thanks

**Comment by klugjo** [comment]
Hi @laisee the new web app version is available in PROD, can you confirm this is fixed ?

**Comment by laisee** [comment]
Will give it a try now - saw the notification about new version earlier today

**Comment by laisee** [comment]
Tested latest version:

The original issue around 'Positions' websocket failure is no longer seen. When net connections are dropped by turning off WIFI for my macbook the 'Orders' web socket turns red after couple of minutes. Did not see any other channel turning off although I waited for 6 mins total. 

Observations:
- 'Orders' web socket automatically reconnects once net access restored by turning WIFI back on. Took about 1-2 mins to go from RED to ORANGE to GREEN
- No other websockets turned red. Should this be happening for all disconnected channels?
- Doing 'soft' refresh with Cmd/R reloads the web page but it sticks on "40%" for about 3-4 mins

<img width="1207" alt="Screenshot 2024-02-07 at 4 01 55 pm" src="https://github.com/Power-Trade/api-docs/assets/5905130/476c54e6-2d58-45f1-8e78-fb3d8ea9f7e7">

- Doing 'hard' refresh with Cmd/Shift/R reloads page without delays, in about 3-6 secs

**Comment by laisee** [comment]
Ran the test for a bit longer, leaving the 'Trade' tab open and checking every few mins on the "connected" UI display

After about 8-10 mins the 'Positions' web socket went red, as before, and stayed red. In other words it didnt re-connect automatically. See below for UI display.  I then turned WIFI and 'Orders' web socket turned orange then red. Once I turned WIFI back on the 'Orders' web socket re-connnected automatically.

<img width="426" alt="Screenshot 2024-02-07 at 4 23 57 pm" src="https://github.com/Power-Trade/api-docs/assets/5905130/acfbda76-a155-4984-984b-7dac97731d1e">

<img width="431" alt="Screenshot 2024-02-07 at 4 24 22 pm" src="https://github.com/Power-Trade/api-docs/assets/5905130/986fc83a-d02b-4255-96df-a2d94f1634df">

The 'Positions' web socket did not reconnect until I made a hard refresh of the page. Still seems to be an issue with this one.

**Comment by klugjo** [comment]
Hi @laisee 

Thanks a lot for the feedback. I added a few new things to help:

1. Idle status:

After one hour, the app will go idle and close all connections. There is a button to reactivate things without reloading
![image](https://github.com/Power-Trade/api-docs/assets/2960040/727a4c42-ede8-454e-ab38-cdb700362148)


2. Disconnect status:

This happens if your network goes down. When it comes back online, an app reload is mandatory as its too hard to know what went offline or not

![image](https://github.com/Power-Trade/api-docs/assets/2960040/cdecee44-0237-4ffb-aeaa-32fc9a526971)


3. A fix for that Positions not reconnecting

I think I have found a bug in the reconnection flow but can't be 100% sure as I am not able to reproduce the error consistently. I appreciate your help and patience in testing that again

**Comment by laisee** [comment]
Thanks for the updates.Will retry a few tests and idle sessions to see how it behaves now.

**Comment by laisee** [comment]
Tested latest version and its working for the most part, but the disconnection after X mins still happening even though I changed nothing about the net connection or browser.

See below, the websockets for 'Order' and 'Positions' disconnected after some time (< 20 mins) of inactivity.
 
<img width="382" alt="Screenshot 2024-02-09 at 10 29 22 am" src="https://github.com/Power-Trade/api-docs/assets/5905130/5c5642f6-cbb9-4d3a-9136-b3aea3ed4c7b">

Showing full view of the web page

<img width="1274" alt="Screenshot 2024-02-09 at 10 29 34 am" src="https://github.com/Power-Trade/api-docs/assets/5905130/d05dae02-8c60-4987-a42f-eca8da606fcb">

Now I turn off WIFI to fully disconnect the app and app responds correctly in 1-2 secs

<img width="639" alt="Screenshot 2024-02-09 at 10 29 57 am" src="https://github.com/Power-Trade/api-docs/assets/5905130/de87937e-6238-4d4a-ae7e-10deb595517c">

Showing full view of the web page while WIFI is OFF

<img width="907" alt="Screenshot 2024-02-09 at 10 30 05 am" src="https://github.com/Power-Trade/api-docs/assets/5905130/c23a48b7-d1b8-4c41-856a-160b689dda0e">

Switching WIFI to ON restores all websocket connections immediately. 
 
<img width="404" alt="Screenshot 2024-02-09 at 10 30 26 am" src="https://github.com/Power-Trade/api-docs/assets/5905130/b6c85daa-5950-4f13-899a-6fc2b53904ba">

Hope this helps.

**Comment by laisee** [comment]
Did one more test. I closed my mac book (OSX/M2) and opened again after 10 secs. Web UI looked like this

<img width="402" alt="Screenshot 2024-02-09 at 10 48 28 am" src="https://github.com/Power-Trade/api-docs/assets/5905130/d49d2bf7-5149-4e49-b614-f043f6bc963c">

I guess its a 'sleep' mode entered for networking when laptop is closed.  And likewise the automatic 'sleep' on networking done by OSX for laptop left open. 

Observations:

- Only seems to affect 'Orders' (sometimes) and 'Positions' (almost all times) though I have not done systematic tests
- PT App doesn't seem to detect this change automatically - needs a hard reload to get all web sockets reconnected
- PT App operates at less than 100% functionality while in this state. I can book trades, which are filled or added to order book but position data is missing and changes to my account health are not provided or updated. This could be dangerous  to PT and/or Traders when adding trades with no idea of position/health impact.

How it looks on account info when positions websocket is disconnected

<img width="388" alt="Screenshot 2024-02-09 at 10 53 43 am" src="https://github.com/Power-Trade/api-docs/assets/5905130/16ddee56-fa5f-4395-acfe-24923df2b4ef">

**Comment by laisee** [comment]
I tested the latest Web UI and its working nicely when loss of network connection occurs. The new UI displays are good and keep the traders informed and in control IMHO.

Let me know if any other testing would be useful, otherwise this looks complete from my side.

**Comment by klugjo** [comment]
Thanks @laisee I am closing this then. We can open a new ticket if needed

**Comment by laisee** [comment]
Cool. UI works nicely for me now.
